# Generated by Django 4.1.7 on 2023-04-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('select gender', 'select gender'), ('male', 'male'), ('female', 'female')], default='select gender', max_length=13)),
                ('image', models.ImageField(blank=True, upload_to='account/')),
            ],
        ),
    ]
