# Generated by Django 4.1.7 on 2023-04-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0011_delete_contactmodel'),
        ('account', '0004_commentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='creted_time',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='watch',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='watch_comment', to='viewapp.watchmodel'),
        ),
    ]
