# Generated by Django 4.1.7 on 2023-04-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_creted_time_commentmodel_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['created_time']},
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
