# Generated by Django 4.1.7 on 2023-04-26 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0011_delete_contactmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_commentmodel_options_commentmodel_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='watch',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viewapp.watchmodel'),
        ),
    ]
