# Generated by Django 4.1 on 2023-04-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.TextField(max_length=150)),
                ('price', models.IntegerField()),
                ('about', models.TextField()),
                ('image_one', models.ImageField(upload_to='watchs/')),
                ('image_two', models.ImageField(blank=True, upload_to='watchs/')),
                ('image_three', models.ImageField(blank=True, upload_to='watchs/')),
                ('added_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
