# Generated by Django 4.1 on 2023-04-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0002_usersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersModel',
        ),
    ]
