# Generated by Django 4.1 on 2023-04-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0005_alter_watchmodel_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
