# Generated by Django 4.1.7 on 2023-04-22 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewapp', '0007_alter_contactmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchBuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_number', models.SmallIntegerField()),
                ('card_number', models.CharField(max_length=16)),
                ('check_code', models.SmallIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='viewapp.watchmodel')),
            ],
        ),
    ]
