# Generated by Django 4.1.7 on 2023-04-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewapp', '0009_watchregistrationmodel_delete_watchbuymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchregistrationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_user_register', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchregistrationmodel',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_register', to='viewapp.watchmodel'),
        ),
        migrations.CreateModel(
            name='WatchBuyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('check_code', models.SmallIntegerField()),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_buy', to='viewapp.watchregistrationmodel')),
            ],
        ),
    ]
