# Generated by Django 4.1.7 on 2023-04-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0010_alter_watchregistrationmodel_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
