# Generated by Django 4.1.7 on 2023-04-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0012_ratingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
