# Generated by Django 4.1.7 on 2023-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0013_delete_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmodel',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
