# Generated by Django 4.1.1 on 2023-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewapp', '0015_watchmodel_about_en_watchmodel_about_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmodel',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
